services:
  webots:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1
    image: webots
    volumes:
    - ./catkin_ws_src:/root/catkin_ws/src:rw
    - ./krock:/root/krock:rw
    - tmp:/tmp:rw
    - /etc/group:/etc/group:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - nvidia_driver_390.48:/usr/local/nvidia:ro
version: '3'
volumes:
  nvidia_driver_390.48:
    external: true
  tmp: null
